version: '3.1'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=sqlite:///project.db
      - SECRET_KEY=secret12435
      - JWT_SECRET_KEY=b6g6ds78ew8
      - PORT=5000
    volumes:
      - db-data:/app/instance
      - media-data:/app/static/media
volumes:
  db-data:
  media-data: